### ISSUE TITLE
Provide API for dec.usaid.gov

### ISSUE THREAD

**Issue by markbrough** [USAID/Feedback#3]
Provide ability to get documents for specific countries/sectors/projects; it would be good to expose the metadata as much as possible (I think you can already get search results in XML).

It would also be great to expose USAID Project IDs wherever they are available, so that the data could eventually be linked back to data published via (e.g.) map.usaid.gov

If project IDs were exposed on map.usaid.gov and dec.usaid.gov, you could probably create a nice (and probably very interesting) mash-up of a geocoded project document search...

**Comment by nicolas-fricke** [comment]
Just started working with the _qsearch API_, looks really promising for a project we're planning to launch. 

Yet, the one thing holding me back from using it is that there is no apparent way to paginate through the results (as @markbrough already mentioned in 2014). Has there been any progress since (@KatataK? )?

**Comment by markecameron** [comment]
Thanks @nicolas-fricke 

The DEC team at USAID very much appreciates your inquiry on the DEC API. They are all excited that people, like you and others, are looking to use the tool to help find information on USAID-funded technical and project materials within DEC’s repository. The DEC team recognized that this is a popular feature request and as of right now, there is minimal movement in adding this feature to the API. However, this feature and other DEC related feature requests are on the roadmap for improvement to the Development Experience Clearinghouse. If this is a critical business requirement, we'd like to get more information regarding your needs so that we could explore other solutions in order to meet the business need. Please email ksc@usaid.gov with additional details and a contact for further discussion.

@markbrough, the DEC API does accept query string that are not encoded as a base64 string. However, the DEC team encourages encoding to base64 to guarantee that the browser transmit the desire query to the DEC’s search engine.  Example: https://dec.usaid.gov/api/qsearch.ashx?q=(Documents.Contract_Grant_Number:(AID-696-LA-11-00001))&rtype=json
